### ISSUE TITLE
CI test_generate_key_with_gpg_import_to_rnp randomly fails

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#550]
## Description

https://travis-ci.org/riboseinc/rnp/jobs/309250885
https://travis-ci.org/riboseinc/rnp/jobs/309253650

```
======================================================================

ERROR: test_generate_key_with_gpg_import_to_rnp (__main__.Keystore)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "cli_tests.py", line 682, in test_generate_key_with_gpg_import_to_rnp

    raise_err('gpg key generation failed', err)

  File "/home/travis/build/riboseinc/rnp/src/tests/cli_common.py", line 22, in raise_err

    raise CLIError(msg, log)

CLIError: None

----------------------------------------------------------------------

Ran 15 tests in 349.051s
```

I haven't spent any time looking at this, but we should get it straightened out soon.

**Comment by ni4** [comment]
I noticed the same recently - from the gpg output it looks like everything is fine but exception is raised.

**Comment by flowher** [comment]
Same with "test_generate_default_rsa_key"

**Comment by ni4** [comment]
Looks like I foind the failure reason of `test_generate_default_rsa_key`, changes are in #581 
gpg key generation most likely fails due to previous deletion of .gpg directory, here is the output:
```
test_generate_key_with_gpg_import_to_rnp (__main__.Keystore) ... /home/travis/local-builds/gpg21-install/bin/gpg --batch --homedir /tmp/rnpctmp0Cb_7K/.gpg --passphrase  --quick-generate-key rsakey@gpg rsa
gpg: keybox '/tmp/rnpctmp0Cb_7K/.gpg/pubring.kbx' created
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
```

Any good ideas how to fix it? @dewyatt proposed to make random .gpg directory for each call. Or probably restart agent after each keyring cleanup?
The problem is that I cannot reproduce this locally.

**Comment by ni4** [comment]
Update: looks like restarting the pgp-agent fixed the issue. Will leave this open for a while to make sure it is solved.

**Comment by dewyatt** [comment]
I can repro it locally in a container. Anyways, regardless of this issue, I think the tests should generally be as isolated as possible to prevent state leak between them. We discussed this before and I think we concluded they should use temporary dirs to avoid timing issues with `gpg-agent`.

**Comment by ni4** [comment]
@dewyatt Yeah, we agreed on that but didn't even create an issue for that :) I just added issue #589.
Right now I just wanted to quick-fix the PR to make sure that all tests are passing.
