### ISSUE TITLE
Broken build in master due to `cli_tests.py`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/rnp#596]
## Description

```
+env RNPC_GPG_PATH=/home/travis/local-builds/gpg21-install/bin/gpg python2 cli_tests.py -w -v
Running in /tmp/rnpctmpdTXfbM
test_rnp_compression (__main__.Compression) ... ok
test_file_encryption__gpg_to_rnp (__main__.Encryption) ... ok
test_file_encryption__rnp_to_gpg (__main__.Encryption) ... ok
test_sym_encryption__gpg_to_rnp (__main__.Encryption) ... ok
test_sym_encryption__rnp_to_gpg (__main__.Encryption) ... ok
test_generate_4096_rsa_key (__main__.Keystore) ... ok
test_generate_default_rsa_key (__main__.Keystore) ... ok
test_generate_key_with_gpg_import_to_rnp (__main__.Keystore) ... gpg key generation failed
gpg key generation failed
ERROR
test_generate_multiple_rsa_key__check_if_available (__main__.Keystore) ... ok
test_generate_with_rnp_import_to_gpg (__main__.Keystore) ... ok
test_armor (__main__.Misc) ... ok
test_encryption_no_mdc (__main__.Misc) ... ok
test_encryption_s2k (__main__.Misc) ... ok
test_gpg_to_rnp_default_key (__main__.SignDefault) ... ok
test_rnp_to_gpg_default_key (__main__.SignDefault) ... ok
test_sign_P256 (__main__.SignECDSA) ... ok
test_sign_P384 (__main__.SignECDSA) ... ok
test_sign_P521 (__main__.SignECDSA) ... ok
test_verify_P256 (__main__.SignECDSA) ... ok
test_verify_P384 (__main__.SignECDSA) ... ok
test_verify_P521 (__main__.SignECDSA) ... ok
======================================================================
ERROR: test_generate_key_with_gpg_import_to_rnp (__main__.Keystore)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cli_tests.py", line 684, in test_generate_key_with_gpg_import_to_rnp
    raise_err('gpg key generation failed', err)
  File "/home/travis/build/riboseinc/rnp/src/tests/cli_common.py", line 22, in raise_err
    raise CLIError(msg, log)
CLIError: None
----------------------------------------------------------------------
Ran 21 tests in 343.512s
FAILED (errors=1)
```

**Comment by ni4** [comment]
Please see #550 
I added fixes to PR #581, but since it will take few more days to be finished I thinking about adding separate PR with cli_tests.py fixes.

**Comment by ronaldtse** [comment]
Here's the latest error on master, relating to AEAD:

```
======================================================================
ERROR: test_sym_encryption__rnp_aead (__main__.Encryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "cli_tests.py", line 906, in test_sym_encryption__rnp_aead
    rnp_sym_encryption_rnp_aead(cipher, size, 6, 'zip')
  File "cli_tests.py", line 476, in rnp_sym_encryption_rnp_aead
    rnp_decrypt_file(enc, dst)
  File "cli_tests.py", line 196, in rnp_decrypt_file
    raise_err('rnp decryption failed', out + err)
  File "/home/travis/build/riboseinc/rnp/src/tests/cli_common.py", line 22, in raise_err
    raise CLIError(msg, log)
CLIError: None

----------------------------------------------------------------------
```

**Comment by ni4** [comment]
@ronaldtse  Thanks, will check. It was passing local tests and Travis. Probably something related to specific file size.

**Comment by flowher** [comment]
I think there is small race condition in this function:
```
def clear_keyrings():
    shutil.rmtree(RNPDIR, ignore_errors=True)
    os.mkdir(RNPDIR, 0700)
    run_proc('kill', ['-9', 'gpg-agent'])
    while os.path.isdir(GPGDIR):
        try:
            shutil.rmtree(GPGDIR)
        except:
            time.sleep(0.1)
    os.mkdir(GPGDIR, 0700)
    run_proc('gpg-connect-agent', ['reloadagent', '/bye'])
```

Function sends a signal to ``gpg-agent``, but it doesn't wait for until agent is process is really killed. In some cases it may take time - in linux SIGKILL will always succeed but it's undefined how long it takes (that's a problem if process is in uninterruptible state).

This case looks like race condition:
https://travis-ci.org/riboseinc/rnp/jobs/334984406

```
test_verify_P3072_Q256 (__main__.SignDSA) ... /home/travis/local-builds/gpg21-install/bin/gpg --gen-key --expert --batch --pinentry-mode loopback --homedir /tmp/rnpctmptDvYCv/.gpg --yes --passphrase password
gpg: keybox '/tmp/rnpctmptDvYCv/.gpg/pubring.kbx' created
gpg: WARNING: some OpenPGP programs can't handle a DSA key with this digest size
gpg: can't connect to the agent: IPC connect call failed
gpg: agent_genkey failed: No agent running
gpg: key generation failed: No agent running
```

**Comment by dewyatt** [comment]
Closing since this ought to be OK now.
