### ISSUE TITLE
Infinite loop on tampered bzip2-compressed signature

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/rnp#673]
## Description

In some of the tests for ruby-rnp I generate random plaintext input, tamper with the resulting signature, and then confirm that verification fails.
On occassion this results in an infinite loop.

Here is an example of a tampered signature that will produce this:
`sig.asc`
```
-----BEGIN PGP SIGNATURE-----

yMECA0JaaDQxQVkmU1k0MLmMAACJ///+8uPkKf6/1/S9P3++pGc9SFXefnfUk3+d
nVwmqHQ1/LAA+bNHeqNNMTI0yMnog0DIAGCGTTQAMQaMTQ0MQGQGgMIxGmmgaHtT
U02pm1RDRpowIyZNqMTTE0NMgaDDSekbRMmQDJgj1ABhAGjBpDQxMIxGCBpg1KaE
9EH6oaaDTRoAAB5I0DQAAAAAGTQNBoD1GQAADTJoM1NPUtUwUBSYQwPAnVhqcncm
hTtEZaBQFghXSoOb2416WX400UVsHZMuVkSj1lByHqAh3ycQL4tJwUKuWgLiUwa4
XKs6zhdww7v56/Pn3VeVgqAk798ACCKG79s/77F2lImDON0GLmCeAT/X9Oe/EGM/
nz6GOiwpWE8Lp29r+w8SNM6fzBLY1PZkcoUUEytMtCNONP7DgHgSIlbI+JmBCRH5
eR0NV0X1aBVxdXu8SzkpzPHrKb57T8mW7lAS5/vRDlIxAI2WIwSZA4kmZE7ycLrv
7wBMlVKkjn8m8NI7fMz/s1JFoSIeriU61h9IvjEUuC3ZIcJIuBXVYmAtghKC2sgl
UtyMUIW2LyQEg/xdyRThQkDQwuYw
=MbJc
-----END PGP SIGNATURE-----
```

```
#0  0x00007fa2059a0dc4 in BZ2_decompress () from /usr/lib/libbz2.so.1.0
#1  0x00007fa2059a4448 in BZ2_bzDecompress () from /usr/lib/libbz2.so.1.0
#2  0x00007fa205bc08c1 in compressed_src_read (src=<optimized out>, buf=<optimized out>, len=32768) at stream-parse.c:401
#3  0x00007fa205bbcf9c in src_peek (src=src@entry=0x55dd45f47218, buf=buf@entry=0x7fff3074ebf3, len=len@entry=1) at stream-common.c:174
#4  0x00007fa205bc3f1e in init_packet_sequence (ctx=ctx@entry=0x7fff3074f790, src=src@entry=0x55dd45f1b588) at stream-parse.c:2192
#5  0x00007fa205bc535b in process_pgp_source (handler=handler@entry=0x7fff30757860, src=src@entry=0x55dd45f1b588) at stream-parse.c:2312
#6  0x00007fa20690bb38 in rnp_process_file (ctx=0x7fff307578f0, in=0x0, out=0x0) at rnp.c:1401
#7  0x000055dd43d58746 in rnp_cmd (cfg=0x7fff307579f8, rnp=<optimized out>) at rnp.c:491
#8  0x000055dd43d577dc in main (argc=2, argv=0x7fff30757e98) at rnp.c:937
```

## Steps to Reproduce

1. `rnp --verify sig.asc` (keys not necessary)

## Expected Behavior

Ideally we would detect that something isn't right and avoid the infinite loop, returning a bad format error or something.

**Comment by ni4** [comment]
@dewyatt Thanks for noticing. I'll fix this.
